### ISSUE TITLE
HTTP session manager

### ISSUE THREAD

**Issue by dlchamp** [OseSem/communitybot#21]
Since the bot will have various commands that require the use of external API endpoints, rather than constructing and closing HTTP session every single time a command is used, we will likely maintain a session that can be used to make these requests over the lifecycle of the bot.

This is a very rough basic idea of what I mean:

Old way:
```py
async with aiohttp.ClientSession() as session:
    async with session.get(some_api_url, headers=some_headers) as r:
        data = await r.json()

# do something with the json data now to display back to the command response.
```

Proposal:
```py
class HTTPBaseClient:
    '''Basic HTTP session manager'''

   def __init__(self, session: aiohttp.ClientSession | None = None) -> None:
       self._session: aiohttp.ClientSession = session or aiohttp.ClientSession()
       self._cache = ... # mayb we can use this to cache some of the respones rather than going out and grabbing one every single time.
 ```
 
 We would have methods to look in cache before going out to make the API request and pass in a custom `Route` object that contains urls, paths, params, headers, etc so we could re-use this class over and over again without having to construct a new one for each API request.
 
 
 Then rather than dealing with json objects within the command callback, we construct various dataclasses that contain our response data and maybe 1-2 optional methods to act upon that data - like for Pokemon types that are converted to emoji, we could do it here which makes it easier to read and more maintainable as we are creating a separation of responsibility.

**Comment by OseSem** [comment]
This is now already made.
