### ISSUE TITLE
Add GHA workflows

### ISSUE THREAD

**Issue by elenakrittik** [OseSem/communitybot#35]
## What would the feature do?*l
This will remove the need for maintainers to checkout every submitted PR just to check if `pre-commit` finds some issues as the same will essentially be done automatically by github.

## Code
You can draw some inspiration (or just blatantly copy-paste, i don't really care haha) from https://github.com/disnake-era/template

## Extras
*N/A*

**Comment by OseSem** [comment]
I added the [pre-commit](https://github.com/apps/pre-commit-ci) bot to run this.
