### ISSUE TITLE
bug: `Localization` seems a little overcomplicated

### ISSUE THREAD

**Issue by elenakrittik** [OseSem/communitybot#36]
## Describe the bug
It looks like it can be easily refactored into a single function on `Bot`.

## Team
> What team would you need this to work at. So for example the team that makes the webiste, the people that make the discord bot itself.

Discord bot team, probably? Not sure i fully understand

## Extras
*N/A*

**Comment by OseSem** [comment]
I like having files in a `utility` folder, so I can find everything and make the code look a lot cleaner. Also the localization is already integrated into the bot as `bot.localization`

**Comment by elenakrittik** [comment]
Fair enough
