### ISSUE TITLE
bug: `log.py`: `get_logger` duplicates `logging.getLogger`

### ISSUE THREAD

**Issue by elenakrittik** [OseSem/communitybot#37]
## Describe the bug
It should probably be removed and the code should use `logging.getLogger` directly.

## Team
Discord bot team?

## Extras
*N/A*

**Comment by OseSem** [comment]
Could you explain this a bit more?

**Comment by elenakrittik** [comment]
The `get_logger` function in `log.py` does nothing but calls `logging.getLogger` with the same arguments, therefore it is unnecessary, should be removed, and all code should be updated to use `logging.getLogger` directly.
