### ISSUE TITLE
bug: `bot.py`: `db` property is unnecessary and question about `on_connect`

### ISSUE THREAD

**Issue by elenakrittik** [OseSem/communitybot#38]
## Describe the bug
Instead of creating a `db` property, we can just assign db session to `CommunityBot.db` instead of `CommunityBit.db_session`. `CommunityBot.on_connect` is empty (and does not call the superclass's `on_connect`), is this intentional or is `on_connect` simply desd code?

## Team
Discord bot team?

## Extras
*N/A*

**Comment by OseSem** [comment]
`on_connect` is just there, because I needed it for something but didn't need it later and I just forgot to remove it. Now it is also here with the **noqa** so I can use it anytime.

**Comment by OseSem** [comment]
@elenakrittik can I close this or is there anything more you'd like?

**Comment by elenakrittik** [comment]
If you don't feel like fixing the `db` property then yes, feel free to.
